[build-system]
requires = ["setuptools>=64", "wheel", "numpy", "matplotlib", "pillow", "tqdm", "h5py", "scipy", "lmfit"]
build-backend = "setuptools.build_meta"

[project]
name = "uedhhlib"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["."]